[amqp]
uri = "amqp://guest:guest@localhost:5672"

[database]
uri = "sqlite:///secpi-database-development.sqlite"

[directories]
__alarms = "./var/spool/alarms"

[global.adam6000]
mqtt_broker_ip = "localhost"
mqtt_topic = "Advantech/11E1DAF0ECCE"
