[worker]

[amqp]
uri = "amqp://guest:guest@localhost:5672"
cacert = "/etc/secpi/certs/ca/cacert.pem"
certfile = "/etc/secpi/certs/worker1.cert.pem"
keyfile = "/etc/secpi/certs/worker1.key.pem"

[global]
