[webserver]
# host = "localhost"
# port = 16677

[amqp]
uri = "amqp://guest:guest@localhost:5672"
cacert = "/etc/secpi/certs/ca/cacert.pem"
certfile = "/etc/secpi/certs/webui.cert.pem"
keyfile = "/etc/secpi/certs/webui.key.pem"

[database]
uri = "mysql+pymysql://secpi:secret@localhost/secpi"
