[amqp]
uri = "amqp://guest:guest@localhost:5672"
cacert = "/etc/secpi/certs/ca/cacert.pem"
certfile = "/etc/secpi/certs/manager.cert.pem"
keyfile = "/etc/secpi/certs/manager.key.pem"

[database]
uri = "mysql+pymysql://secpi:secret@localhost/secpi"

[directories]
__alarms = "/var/spool/secpi/alarms"

[global]
