[main]
worker_id = 1
active = true
config_no_update = true

[amqp]
uri = "amqp://guest:guest@localhost:5672"

[global.adam6000]
mqtt_broker_ip = "localhost"
mqtt_topic = "Advantech/11E1DAF0ECCE"


# Action items
[[actions]]
id = 1
name = "test-action-1"
module = "test"
class = "TestAction"
active_state = true
params = { msg = "foobar" }

[[actions]]
id = 2
name = "test-action-2"
module = "test"
class = "TestAction"
active_state = false
params = { msg = "bazqux" }


# Sensor items
[[sensors]]
id = 1
name = "tcp-listener-1234"
module = "network"
class = "TCPPortListener"
params = { ip = "localhost", port = "1234" }
