[amqp]
uri = "amqp://guest:guest@localhost:5672"

[database]
#uri = "sqlite:///secpi-database-testing.sqlite"
uri = "mysql+pymysql://secpi:secret@localhost/secpi_test"

[directories]
__alarms = "/tmp/secpi-testing/alarms"

[global.adam6000]
mqtt_broker_ip = "localhost"
mqtt_topic = "Advantech/11E1DAF0ECCE"
