[webserver]
# host = "localhost"
# port = 16677

[amqp]
uri = "amqp://guest:guest@localhost:5672"

[database]
#uri = "sqlite:///secpi-database-testing.sqlite"
uri = "mysql+pymysql://secpi:secret@localhost/secpi_test"