#!/bin/sh

### BEGIN INIT INFO
# Provides:          secpi-webinterface
# Required-Start:    $remote_fs $syslog $named
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SecPi Webinterface
# Description:       This starts and stops the SecPi Webinterface.
### END INIT INFO

# Author: Philip Woelfel <is141524@fhstp.ac.at>, Martin Liebl <is141513@fhstp.ac.at>
# Original script by: http://blog.scphillips.com/posts/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/

DIR=/opt/secpi
DAEMON=$DIR/webinterface/main.py
DAEMON_NAME=secpi-webinterface

# Add any command line options for your daemon here
DAEMON_OPTS="$DIR"

# This next line determines what user the script runs as.
DAEMON_USER={{DEAMONUSER}}

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0



