from .actionparams import ActionParamsPage
from .actions import ActionsPage
from .alarmdata import AlarmDataPage
from .alarms import AlarmsPage
from .logs import LogEntriesPage
from .notifierparams import NotifierParamsPage
from .notifiers import NotifiersPage
from .sensorparams import SensorParamsPage
from .sensors import SensorsPage
from .setups import SetupsPage
from .setupszones import SetupsZonesPage
from .workers import WorkersPage
from .workersactions import WorkersActionsPage
from .zones import ZonesPage
