name: Tests

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]  # "macos-latest", "windows-latest"
        python-version: [ "3.7", "3.8", "3.9" ]  # "3.10", "3.11-dev"

    env:
      OS_TYPE: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    services:

      garagemq:
        image: amplitudo/garagemq
        ports:
          - 5672:5672

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |

        # Install `socat` and `amqp-publish`.
        sudo apt-get update
        sudo apt-get install --yes socat amqp-tools

        # Verify installation.
        socat -V
        amqp-publish --usage

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |

        # Install `socat` and `amqp-publish`.
        brew install rabbitmq socat

        # Verify installation.
        socat -V
        amqp-publish --usage

    - name: Acquire sources
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Setup project
      run: |

        # `setuptools 0.64.0` adds support for editable install hooks (PEP 660).
        # https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6400
        pip install "setuptools>=64" --upgrade
        
        # Install package in editable mode.
        pip install --editable=.[test]
        
    - name: Run tests
      run: |
        pytest

    - name: Upload coverage results to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
